menu:
  Home: /
  Archives: /archives
  About: http://shanzi.github.io

widgets:
- search
- category
- tagcloud

excerpt_link: Read More

fancybox: true

follow_me:
  twitter: ant_sz
  github: shanzi
  gplus: ChaseZhang
  facebook: yunerrun

comment_provider: disqus
