menu:
  Home: /
  Archives: /archives
  About: http://shanzi.github.io

widgets:
- search
- category
- tag

excerpt_link: Read More

twitter:
  username: ant_sz
  show_replies: false
  tweet_count: 5

addthis:
  enable: true
  pubid: ra-52e93dfc1e377605

fancybox: true


comment_provider: disqus
